# Site settings
title: Pictures and spelling errors
header-img: img/Maasvallei1.jpg
email: joep.driesen@seasoning.be
description: "Writing about my travels"
baseurl: "/Travels"
url: "http://www.joep.tk"
github_username:  Gargamel1989

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]